"""liboqs <-> reference interop (the constant-time swap, security review #7).

Both backends implement final FIPS 203 ML-KEM-768, so keys and ciphertexts must interoperate:
a key generated by the reference must decapsulate a liboqs ciphertext and vice versa. These tests
run only where liboqs is installed (hosted nodes); on dev machines they skip.
"""

import pytest

pytest.importorskip("oqs")

import oqs  # noqa: E402
from kyber_py.ml_kem import ML_KEM_768  # noqa: E402

from atlas.crypto import kem  # noqa: E402

ALG = "ML-KEM-768"


def test_backend_is_liboqs_and_guard_passes():
    assert kem.KEM_BACKEND == "liboqs"
    assert kem.KEM_CONSTANT_TIME is True
    kem.require_constant_time_kem()          # public exposure now permitted — no raise


def test_reference_key_decaps_liboqs_ciphertext():
    ek, dk = ML_KEM_768.keygen()             # reference keypair
    ct, ss = oqs.KeyEncapsulation(ALG).encap_secret(ek)      # liboqs encapsulates to it
    assert ML_KEM_768.decaps(dk, ct) == ss                   # reference recovers the same secret


def test_liboqs_key_decaps_reference_ciphertext():
    k = oqs.KeyEncapsulation(ALG)
    ek = k.generate_keypair()                # liboqs keypair
    ss, ct = ML_KEM_768.encaps(ek)           # reference encapsulates to it
    assert oqs.KeyEncapsulation(ALG, secret_key=k.export_secret_key()).decap_secret(ct) == ss


def test_hybrid_roundtrip_on_native_backend():
    kp = kem.generate_keypair()
    enc = kem.encapsulate(kp.public)
    assert kem.decapsulate(kp, enc.mlkem_ct, enc.x25519_eph_pk) == enc.shared


def test_seeded_keygen_interops_with_native_decap_path():
    # keypair_from_seed stays on the reference derandomised keygen; its keys must work
    # through the (liboqs) encap/decap path.
    kp = kem.keypair_from_seed(b"\x42" * 32)
    enc = kem.encapsulate(kp.public)
    assert kem.decapsulate(kp, enc.mlkem_ct, enc.x25519_eph_pk) == enc.shared
