import XCTest
@testable import AtlasCore

/// The finish line: a proof GENERATED BY THE PYTHON BACKEND verifies on the phone (Swift/blst),
/// byte-for-byte. The Fiat-Shamir challenge hashes only G1/G2 elements + scalars (all cross-language
/// identical), so the two implementations agree with no shared field representation.
final class AnonCredInteropTests: XCTestCase {
    private func g1(_ h: String) -> G1 { G1.deserialize(Array(hex: h))! }
    private func g2(_ h: String) -> G2 { G2.deserialize(Array(hex: h))! }
    private func fr(_ h: String) -> Fr { Fr(reducingBE: Array(hex: h)) }

    func testVerifyPythonGeneratedProof() {
        // vector generated by backend/atlas/realid/anon_accreditation.py (claim "work:BSc", nonce "nonce")
        let XT = "19c313a61153120103feb64bd4cf0f995775f2b4f66f8908879ff088d02d3851b732d9fca7db4b07e695cea45f07fcb80673f0d95d74cbfdaa29353f256e21106a39848e5d5fdabcf9d24e675eeb4372fdf495dd0f7def7265e957988b0eddf5027a7cb6ee6505138caac7afdd28bb54d486c0349e38060f4db15c62d97e12aa6a4ecdaaa0c10d7074293549543d445517750ccff95499bec21410dd9794498dff2d0aa235998d61cdbf88a738fe0dbe5fcdb5cfd098c59e0dc91fa5fe116898"
        let Y0 = "175ed6b9fb1ac3866b54973c9ad7cfab0f7fcc7f278d52b235566cfc2addfe91667ebebb19d59c7fb88b2fefcaa19ba7103c644f42be8ac3b562443f7c911e48c5aeb07beda174aa2ee6a35798dc2ccb09649b610a1c42110a34c0a6fb2b0431102f5a41fc882c3fc00517ddf5db57388c7703ec0d38d7a384ee19fbdd2d251fe07154e0c8cbe3c947d45107ebf05d7e0d9dd06f3435fea8fc60185093eb60bedfae772de01a26fb6624a64aa8ea8f9f48a0a04c7f0410710c0e2399ed1a4c4b"
        let Y1 = "05d1f5b5192d8d3480e49e0041970f49d0a3330f136691cc02457fe329a909caceda711c8e4590fce0ab8871d3b105410bd869fdf7d89a618e4e3c6c73aa54b9486e7094bf69c39e2ff3d3f3338b5fb674ab9a7a48f2029a834f014cb61d3725144c0e06ef9da1733745625b750fb949b5be3324cdee7d76afee2b533e5a81caa953272f9ee215f5a2001af72b29bb03146070f167d5bc10ff91c02b1abd3321009a32a853ab6e14d24387619347477b307809ba9a2c844dcee59c9e70ec2dd9"
        let S1 = "0429d163b59d979158a4cf19445421a1fe524f2f04222c4e71bc1dc2f05b19657f41f341df5b72147701b46ef67e7c3c1774a04f58a527bdc7e7d4b7887db56f0403dbf536386c76574ce97f4a0649795cabf25c487fb49ab6ccea22a716bc4e"
        let S2 = "0e6f340c8a093042489fb5af36c27b2672b21ccff4935208702a1777ae83daa2c18184635ccfa5de3c121f2ded142614036d30ece1dd0c99d67c6b80e9b73e36a73327b1ba176c6f69aee9c24b28780663f6dd20190a364bf11befb2d35ea4dc"
        let RC = "19b045088258cf7782d4ad6410a9706c66dd5b3e6e0230c6f83b1cd9b58acf52cce59993f603045150ff429d2c9a88e014d8cab13db02e54707ff19aff31619865b67b3158070b1cc3d55095d90c45b8101b2982d016e029d32092f3466f6a010002239ec7725baaa4b7540bceaeaeb45122d33f764ce17805681a4d1ef15798be84a48df378c2d418d94826db9580d107e17d1d4080469136a72d95d0f6889523b06862e250742187cbba474107ae880fdcb60641caa896d54fa876ae08716a"
        let Z0 = "6ce474ab5b4d0e42fe8cb7cfb0cfc72c59e0f7adc6a5ccfa6f53bcbb17051d30"
        let ZT = "453e95ab29c2d1d18cb51181def260f180b10d79101ab41bafbdd977bc36e95e"
        let CH = "1cd72069823d54514e289f0a8be9144ef6572ea9d2295d6931e43ce77521184d"

        let pub = PS.PublicKey(Xt: g2(XT), Yt: [g2(Y0), g2(Y1)], Yg1: [], n: 2)
        let proof = PS.Proof(s1: g1(S1), s2: g1(S2), commitment: g2(RC), reveal: [0],
                             revealedVals: [Fr.msg("work:BSc")], responses: [fr(Z0), fr(ZT)], challenge: fr(CH))
        XCTAssertTrue(AnonCred.verify(pub, proof, claim: "work:BSc", nonce: Data("nonce".utf8)))
        // sanity: a different claim must not verify the same proof
        XCTAssertFalse(AnonCred.verify(pub, proof, claim: "work:MSc", nonce: Data("nonce".utf8)))
    }

    /// The full revocable showing (credential AND non-revoked, handle-bound) generated by the Python
    /// backend (anon_revocable.py) verifies here on Swift/blst.
    func testVerifyPythonRevocableProof() {
        let XT = "153297a9b580653345a4c4996a00444dccb7f30aa648f28182c639f7b34697e825c2cc6983344b39b020004efdd1171c13216c9bb04bd75b7b0880c96631a245152719d11ce49b6d107af17a67557b9106b8f0392a093a5ae2f4771007af56980060b08599954b03c79e53e97d02e234810b7e317412cf842ff29e751f94f03144a3df4325701abc103fc7a51939d78315e319e341350de03c1c325670c7911d34f6cb95ab4d1ddc3cb04adb109d5c9594bd819235e9beadb2cef61ca68d0809"
        let Y0 = "1467079e2222a2e3c92e4e2ee8e005bfdf580525b7a04800764710a3e507387b283caab62ee528da152d0c22b90adfab143fd8f41fd548287545b47606afdefc930cbd9dd59d7fb80e4239d18bd08ffa009aa56496d138f3d20d6b8854957c2704ad855c6cac299fe6389f6fd3cc6c1cc3fd43d1681391184a88bc76bf56c585164f02d10b44fc13d4f70790121b0b8308adfca4be34c1ec33ac48c9217b0a2e1fef1e29a56705058cc088cb1873a535beb76a515752b0b563c2cad52e2c352d"
        let Y1 = "1269ab3b03c7bce122d9ee5ddc22e85f3700626ce76d79a01b90c57ce6e356fc52192a03276d113e0f638c5b40935eb50e68ea6aa9010a59964cc71f33571c83895191ac9b27bbc4507d66b5ca7ee25fa2ab37fba51f2f778148c235ba5b3df00fc7fe8abfc8cb7804e114505d140cf0d66f0b2c59e75cc55298a8fe55bfd13c8bd33eaac9cc755dca52d21d78b14e5b06249fa89bcc79366fd842422eec9903ba96635bf1773c8a6bf36d61ae9e112dc0cf955af49fb8f3f9460271dfe0c22a"
        let Y2 = "14de8e61b775b7450404d9865faa7aa7eaf4015462b8050fc1bdf59f5d9b966d986123ff954162bdf5fa94e19040c5980834e75a54f04f8be8111665dd5c82cb8bec8f0ebf2477e8afecb52c22d185cd627d230b57b1e814fae759440d772d380c50bdf42c93deaabd347ad46e9f7be57c043c9d0318deaf1c7d3abb67ad9a9ac5605c941aacccaabc709e97bdc12593181b2698599cafe7070af5f1aff06f68256d2d8e28c3546d9c1fb1282309688310982de38f897002e1a5ab00c69a64ed"
        let AP = "1613f8e46251b89541ea076f27f3320a3f978f6a6c0dea10fa0db15665da83c11191e53a00a9500b9f9b1aec3a9a49760eab901dd57bcd4b05b0ff512ecee194217b1729d65ca15aa582333cb4e674a3bcdafd2637ad05f3170f98956fbd536c0c4f2bd71fb9066265ae402adb0cea28b91630d077c90c96eedd09b1524a813d2f6a78decb8a139497f0147016df15560ea10a0017a10d71e8c9bc01adac505495df14af0f0bedd52a18a90212c72802a8d161b04a500007d822ac2c234f4909"
        let AC = "062311d1753139ed0a1ddc79d91845425a912866da3cfef96d7e572a9ba9290bf6417c0054c48ec46064f4117d83ceb916e2491258d45ab1d06142a968a0d9dfb17d18c961e7c30acc7ab2218538d0e3d8470e9e4b42f4cd7c1faa982ea88091"
        let S1 = "0290071c0888801aa9354d57a5ec5c4adcd39cfb8c5bb29a51dd95acbe64bc38beb705824048c189606241ac6e02ade90bb5613265c951c16750f95f18f3a0553374ca4d88913d21d42a13929ea742f79aedb5528ec2330c6de9408b9708016b"
        let S2 = "085137725d32b09dcf7e85937a42328095d75c8db7c5cd2eae9fb04d067e859d7f2ff2bace5c813c667cadf49d1a9cdb01e7d59f2112928e9845812b87f3b14e558891400abd149b002cd46ea11d464d07002fc0b4dd5b0999cdc18118bc6b2b"
        let WB = "07cfa0a197a0d99ccaeba606cee60d38559ba79c2342e8fa31b7c33c150fc5d51e01d879a648df12292b944cf08a10b90b5e624e9596518af6249b3d2188abb8ae0cb82b26ec01bdd594fab86489cfcdc8d94610833b5abad22bb0e0a75b58e4"
        let RP = "0102b78caec366ed4f8a9a23fac3fee6f7672194623ca97ba9b0eafcf21500bea89f7800fee51072ad286fbce0ef541f0d7571ebb9f8ea2fd586b3fb8bc2e6c1038b9de493abf2364a944a0e04326b35d9e60b3fb4214b78f39c2d00d3f16a50055aa1ad4e3ecbfe2863e03728684269b9f4e27203b96347170eec05d42a6f186d108d6d2a08f7da031bea90394861a907484a790be8b0c1385eeb4800c821fe862ff0e9facf90ac23bff72808d79efd2b7b479d52b2dc9131f2c11d5120e945"
        let RM = "080c516b3d01e573bf2574d7fb8c95c65bbd2cd0feaabd3ff1dc47177e9b6a752edac61769ab4dc624e6201fd864925f10652edac5e3986ba740e80ff1729df2a7fa213c15fc6644c8b50c67502465fafa7f6fb4c3c75fc137b79ccf6af16e9d"
        let C = "370a938ed9631abe514023953bbe4068d413403b382f0bec00047c7cc744d3c4"
        let ZM = "69f3f3363e45705c540df241310164487043812e7000d79b9a96d5c9de6883f1"
        let ZH = "20d9996e561fdd3d8312a09db6fbd68a074c917c0168228cc2a6b57b18ec0372"
        let ZT = "3c87018ee562e982bd0924793c906694939b6acba147b061aa29e8f1bdf6ded9"
        let ZR = "64f64c85e1927a0dc57bb234443c47a3b8ac5c8c649fb19e0e7fe58b5132c57f"

        let pub = PS.PublicKey(Xt: g2(XT), Yt: [g2(Y0), g2(Y1), g2(Y2)], Yg1: [], n: 3)
        let proof = Revocable.Proof(s1: g1(S1), s2: g1(S2), wbar: g1(WB), rPs: g2(RP), rMem: g1(RM),
                                    c: fr(C), zMs: fr(ZM), zHandle: fr(ZH), zT: fr(ZT), zRho: fr(ZR))
        XCTAssertTrue(Revocable.verify(pub, accPub: g2(AP), accumulator: g1(AC), proof,
                                       claim: "work:BSc", nonce: Data("nonce".utf8)))
        XCTAssertFalse(Revocable.verify(pub, accPub: g2(AP), accumulator: g1(AC), proof,
                                        claim: "work:MSc", nonce: Data("nonce".utf8)))
    }
}

private extension Array where Element == UInt8 {
    init(hex: String) {
        var out = [UInt8](); out.reserveCapacity(hex.count / 2)
        var i = hex.startIndex
        while i < hex.endIndex {
            let j = hex.index(i, offsetBy: 2)
            out.append(UInt8(hex[i..<j], radix: 16)!)
            i = j
        }
        self = out
    }
}
