import XCTest
@testable import AtlasCore

/// Economy engine (Swift), parity with `backend/atlas/economy/` (Python reference of record).
/// The pinned KAT numbers were GENERATED by running the Python reference under .venv313 and are
/// hardcoded here so the two implementations are number-locked. See the task report for the exact
/// vectors and the `python -c` snippets that produced them.
final class EconomyParityTests: XCTestCase {

    private func tag(_ i: Int) -> Data { Data("p\(i)".utf8) }

    private func pool(persons: Int, epoch: Int = 5, activity: Int = 1) throws -> PoLEPool {
        let p = PoLEPool()
        for i in 0..<persons {
            try p.add(try collectPoLE(personTag: tag(i), epoch: epoch,
                                      entropyCommit: Data("env".utf8), live: true,
                                      activityWeight: activity))
        }
        return p
    }

    // MARK: - Coin

    func testCoinTransferKAT() throws {
        // KAT: mint 1000 to a, transfer 300 a->b  => a=700 b=300 supply=1000
        let c = Coin()
        try c.mint("a", 1000)
        try c.transfer("a", "b", 300)
        XCTAssertEqual(c.balance("a"), 700)
        XCTAssertEqual(c.balance("b"), 300)
        XCTAssertEqual(c.supply, 1000)
        // account_for(0x010203) == "p:010203"
        XCTAssertEqual(Coins.accountFor(Data([1, 2, 3])), "p:010203")
    }

    func testCoinLedgerErrors() throws {
        let c = Coin()
        try c.mint("a", 100)
        XCTAssertThrowsError(try c.transfer("a", "b", 0))
        XCTAssertThrowsError(try c.transfer("a", "b", 101))
        XCTAssertThrowsError(try c.mint("a", -1))
        try c.transfer("a", "a", 50)     // self-transfer no-op
        XCTAssertEqual(c.balance("a"), 100)
    }

    // MARK: - PoLE pool

    func testPoolDedupeAndHighestActivity() throws {
        let p = PoLEPool()
        try p.add(try collectPoLE(personTag: tag(0), epoch: 1, entropyCommit: Data(), live: true, activityWeight: 1))
        try p.add(try collectPoLE(personTag: tag(0), epoch: 1, entropyCommit: Data(), live: true, activityWeight: 4))
        try p.add(try collectPoLE(personTag: tag(0), epoch: 1, entropyCommit: Data(), live: true, activityWeight: 2))
        XCTAssertEqual(p.persons, 1)
        XCTAssertEqual(p.activityOf(tag(0)), 4)          // highest wins, presence never inflated
        XCTAssertThrowsError(try collectPoLE(personTag: tag(1), epoch: 1, entropyCommit: Data(), live: false))
    }

    // MARK: - policy.issue

    func testIssueKAT() throws {
        // KAT: 10 persons activity 1, col=100 value=10000 tithe=0, supply=1_000_000, default params
        let r = try Policy.issue(try pool(persons: 10), colIndex: 100, valueIndex: 10000,
                                 titheInflow: 0, state: EconomyState(supply: 1_000_000))
        XCTAssertEqual(r.epoch, 5)
        XCTAssertEqual(r.persons, 10)
        XCTAssertEqual(r.ubiPerPerson, 100)
        XCTAssertEqual(r.ubiTotal, 1000)
        XCTAssertEqual(r.vrpTotal, 3500)
        XCTAssertEqual(r.foundationTotal, 500)
        XCTAssertEqual(r.titheUsed, 0)
        XCTAssertEqual(r.minted, 5000)
        XCTAssertEqual(r.controls, [])
        XCTAssertEqual(r.newSupply, 1_005_000)
    }

    func testIssueValueBelowParKAT() throws {
        // KAT: 4 persons, col=50 value=5000 tithe=200 supply=1_000_000
        let r = try Policy.issue(try pool(persons: 4, epoch: 9), colIndex: 50, valueIndex: 5000,
                                 titheInflow: 200, state: EconomyState(supply: 1_000_000))
        XCTAssertEqual(r.ubiPerPerson, 100)
        XCTAssertEqual(r.ubiTotal, 400)
        XCTAssertEqual(r.vrpTotal, 1400)
        XCTAssertEqual(r.foundationTotal, 200)
        XCTAssertEqual(r.titheUsed, 200)
        XCTAssertEqual(r.minted, 1800)
        XCTAssertEqual(r.controls, ["value_below_par", "tithe_backed"])
        XCTAssertEqual(r.newSupply, 1_001_800)
    }

    func testLowColMoreVrpVsHighColMoreUbi() throws {
        // KAT: small supply=2000 so the 5% growth cap (=100) binds.
        // col=2  -> UBI small (20), VRP funded (70), no controls
        // col=40 -> UBI floor (400) crowds VRP to 0, throttled + exceeds cap
        let lo = try Policy.issue(try pool(persons: 10, epoch: 1), colIndex: 2, valueIndex: 10000,
                                  titheInflow: 0, state: EconomyState(supply: 2000))
        XCTAssertEqual(lo.ubiTotal, 20)
        XCTAssertEqual(lo.vrpTotal, 70)
        XCTAssertEqual(lo.foundationTotal, 10)
        XCTAssertEqual(lo.minted, 100)
        XCTAssertEqual(lo.controls, [])

        let hi = try Policy.issue(try pool(persons: 10, epoch: 1), colIndex: 40, valueIndex: 10000,
                                  titheInflow: 0, state: EconomyState(supply: 2000))
        XCTAssertEqual(hi.ubiTotal, 400)
        XCTAssertEqual(hi.vrpTotal, 0)
        XCTAssertEqual(hi.minted, 400)
        XCTAssertEqual(hi.controls, ["vrp_throttled", "ubi_exceeds_growth_cap"])
    }

    func testIssueValidation() throws {
        XCTAssertThrowsError(try Policy.issue(try pool(persons: 1), colIndex: 1, valueIndex: 0,
                                              state: EconomyState()))
        XCTAssertThrowsError(try Policy.issue(try pool(persons: 1), colIndex: 1, valueIndex: 100,
                                              titheInflow: -1, state: EconomyState()))
    }

    // MARK: - distribute_vrp

    func testDistributeVrpKAT() throws {
        // KAT: activity weights p0=1,p1=3,p2=2 (total 6), vrp_total=1000
        // => p0=166, p1=500, p2=333 (floor); dust = 1000-999 = 1 -> Foundation
        let p = PoLEPool()
        try p.add(try collectPoLE(personTag: Data("p0".utf8), epoch: 1, entropyCommit: Data("e".utf8), live: true, activityWeight: 1))
        try p.add(try collectPoLE(personTag: Data("p1".utf8), epoch: 1, entropyCommit: Data("e".utf8), live: true, activityWeight: 3))
        try p.add(try collectPoLE(personTag: Data("p2".utf8), epoch: 1, entropyCommit: Data("e".utf8), live: true, activityWeight: 2))
        XCTAssertEqual(p.totalActivity, 6)
        let d = Dictionary(uniqueKeysWithValues: Policy.distributeVrp(p, vrpTotal: 1000))
        XCTAssertEqual(d[Data("p0".utf8)], 166)
        XCTAssertEqual(d[Data("p1".utf8)], 500)
        XCTAssertEqual(d[Data("p2".utf8)], 333)
        XCTAssertTrue(Policy.distributeVrp(p, vrpTotal: 0).isEmpty)
    }

    // MARK: - apply_issuance (supply conservation)

    func testApplyIssuanceConservesSupplyAndFloor() throws {
        let p = try pool(persons: 10)
        let r = try Policy.issue(p, colIndex: 100, valueIndex: 10000, titheInflow: 0,
                                 state: EconomyState(supply: 1_000_000))
        let coin = Coin()
        try Policy.applyIssuance(coin, result: r, pool: p)      // tithe budget 0 -> all minted
        // Each person receives the uniform UBI floor (100) PLUS an equal VRP share (3500/10=350).
        XCTAssertEqual(coin.balance(Coins.accountFor(tag(0))), 450)
        // Supply grows by exactly `minted`; total credited == ubi + vrp + foundation.
        XCTAssertEqual(coin.supply, r.minted)
        let credited = coin.accounts().values.reduce(0, +)
        XCTAssertEqual(credited, r.ubiTotal + r.vrpTotal + r.foundationTotal)
    }

    func testApplyIssuanceTitheIsSupplyNeutral() throws {
        // With a tithe pre-funding the whole issuance, no new supply is minted.
        let p = try pool(persons: 4, epoch: 9)
        let r = try Policy.issue(p, colIndex: 50, valueIndex: 5000, titheInflow: 200,
                                 state: EconomyState(supply: 1_000_000))
        let coin = Coin()
        try coin.mint("tithe", r.titheUsed)                     // businesses paid this earlier
        let supplyBefore = coin.supply
        try Policy.applyIssuance(coin, result: r, pool: p)
        XCTAssertEqual(coin.supply - supplyBefore, r.minted)
    }

    // MARK: - simulate

    func testSimulateCarriesSupplyForward() throws {
        let out = try Policy.simulate([
            .init(epoch: 1, persons: 10, col: 100, value: 10000),
            .init(epoch: 2, persons: 10, col: 100, value: 10000),
        ])
        XCTAssertEqual(out.count, 2)
        // Genesis: supply 0 -> cap 0 -> no VRP headroom, only the UBI floor mints (1000).
        XCTAssertEqual(out[0].newSupply, 1000)
        XCTAssertEqual(out[0].minted, 1000)
        XCTAssertEqual(out[1].newSupply, 2000)
        XCTAssertEqual(out[1].newSupply, out[1].minted + out[0].newSupply)
    }

    // MARK: - governance

    func testGovernanceMedianKAT() throws {
        // KAT: 5 certified voters, epoch 7, one extreme outlier (99999/1).
        // median cols -> 105 ; median values -> 9800
        let g = IndexGovernance(quorum: 3)
        for v in ["n1", "n2", "n3", "n4", "n5"] { g.certify(v) }
        let votes = [
            IndexVote(voter: "n1", epoch: 7, col: 100, value: 10000),
            IndexVote(voter: "n2", epoch: 7, col: 110, value: 9500),
            IndexVote(voter: "n3", epoch: 7, col: 105, value: 10200),
            IndexVote(voter: "n4", epoch: 7, col: 99999, value: 1),
            IndexVote(voter: "n5", epoch: 7, col: 90, value: 9800),
        ]
        let (col, value) = try g.ratify(votes, epoch: 7)
        XCTAssertEqual(col, 105)
        XCTAssertEqual(value, 9800)
        // median helper KAT: even -> 25, odd -> 3
        XCTAssertEqual(economyMedian([10, 20, 30, 40]), 25)
        XCTAssertEqual(economyMedian([5, 1, 3]), 3)
    }

    func testGovernanceQuorumAndDedupe() throws {
        let g = IndexGovernance(quorum: 3)
        g.certify("n1"); g.certify("n2")
        XCTAssertThrowsError(try g.ratify([
            IndexVote(voter: "n1", epoch: 1, col: 100, value: 10000),
            IndexVote(voter: "n2", epoch: 1, col: 100, value: 10000),
            IndexVote(voter: "n3", epoch: 1, col: 100, value: 10000),   // not certified
        ], epoch: 1))
        // last submission per voter wins (dedupe)
        g.certify("n3")
        let (col, _) = try g.ratify([
            IndexVote(voter: "n1", epoch: 1, col: 100, value: 10000),
            IndexVote(voter: "n2", epoch: 1, col: 200, value: 10000),
            IndexVote(voter: "n3", epoch: 1, col: 1, value: 10000),
            IndexVote(voter: "n3", epoch: 1, col: 300, value: 10000),   // overrides n3
        ], epoch: 1)
        XCTAssertEqual(col, 200)     // median of {100,200,300}
    }

    // MARK: - onramp

    func testOnrampKAT() throws {
        // KAT: fiat 5000 * rate 3 = 15000 APLC; reserve holds 5000 USD; supply 15000
        let coin = Coin(); let res = FiatReserve()
        let credited = try depositFiat(coin, res, buyer: "p:beef", fiatAmount: 5000,
                                       currency: "USD", aplcPerFiat: 3)
        XCTAssertEqual(credited, 15000)
        XCTAssertEqual(coin.balance("p:beef"), 15000)
        XCTAssertEqual(coin.supply, 15000)
        XCTAssertEqual(res.held("USD"), 5000)
        XCTAssertThrowsError(try depositFiat(coin, res, buyer: "x", fiatAmount: 0, currency: "USD", aplcPerFiat: 3))
        XCTAssertThrowsError(try depositFiat(coin, res, buyer: "x", fiatAmount: 10, currency: "USD", aplcPerFiat: 0))
    }

    // MARK: - redemption (closed loop)

    func testClosedLoopRefusesCashOut() throws {
        let coin = Coin(); let res = FiatReserve()
        try coin.mint("p:1", 1000)
        XCTAssertThrowsError(try ClosedLoop().redeem(coin, res, holder: "p:1", aplcAmount: 100, currency: "USD")) {
            XCTAssertEqual($0 as? ClosedLoopError, .offRampClosed)
        }
        XCTAssertThrowsError(try FiatRedemption().redeem(coin, res, holder: "p:1", aplcAmount: 100, currency: "USD")) {
            XCTAssertEqual($0 as? ClosedLoopError, .notImplemented)
        }
    }

    // MARK: - commerce

    func testCommerceFeeKAT() throws {
        // KAT: amount=12345 fee_bp=300 -> fee=370; seller=11975 tithe=370 buyer=100000-12345=87655
        let coin = Coin(); try coin.mint("buyer", 100_000)
        let sale = try Commerce.purchase(coin, buyer: "buyer", seller: "seller",
                                         item: Data("widget".utf8), amount: 12345, epoch: 2)
        XCTAssertEqual(sale.fee, 370)
        XCTAssertEqual(coin.balance("seller"), 11975)
        XCTAssertEqual(coin.balance("tithe"), 370)
        XCTAssertEqual(coin.balance("buyer"), 87655)
        XCTAssertEqual(Commerce.fee(12345, 300), 370)
        XCTAssertEqual(Commerce.defaultFeeBp, 300)
    }

    func testBookingOncePerSlot() throws {
        let coin = Coin(); try coin.mint("buyer", 10_000)
        let book = Commerce.BookingBook()
        XCTAssertTrue(book.isFree("barber", Data("cut".utf8), "9am"))
        _ = try book.book(coin, buyer: "buyer", provider: "barber", service: Data("cut".utf8),
                          slot: "9am", amount: 1000, epoch: 1)
        XCTAssertFalse(book.isFree("barber", Data("cut".utf8), "9am"))
        XCTAssertThrowsError(try book.book(coin, buyer: "buyer", provider: "barber",
                                           service: Data("cut".utf8), slot: "9am", amount: 1000, epoch: 1))
    }

    func testPurchaseInsufficientBalance() throws {
        let coin = Coin(); try coin.mint("buyer", 100)
        XCTAssertThrowsError(try Commerce.purchase(coin, buyer: "buyer", seller: "s",
                                                   item: Data(), amount: 200, epoch: 1))
    }

    // MARK: - transparency

    func testTransparencyGatingAndChain() throws {
        let coin = Coin(); try coin.mint("cust", 100_000)
        let ledger = Transparency.TransparencyLedger()
        // anonymous registration refused
        XCTAssertThrowsError(try ledger.registerBusiness("shady", identified: false))
        // recording before identification refused
        XCTAssertThrowsError(try ledger.record(business: "shop", kind: "sale", amount: 1, fee: 0,
                                                counterparty: "cust", epoch: 1))
        try ledger.registerBusiness("shop", identified: true)
        _ = try Transparency.businessSale(coin, ledger, seller: "shop", buyer: "cust",
                                          item: Data("a".utf8), amount: 1000, epoch: 1)
        try Transparency.businessListingFee(coin, ledger, business: "shop", amount: 50, epoch: 1)
        // selling as an unidentified business is refused
        XCTAssertThrowsError(try Transparency.businessSale(coin, ledger, seller: "ghost",
                                                           buyer: "cust", item: Data(), amount: 10, epoch: 1))
        // append-only chain verifies; audit returns both entries
        XCTAssertTrue(ledger.verifyChain())
        XCTAssertEqual(ledger.audit("shop").count, 2)
        XCTAssertEqual(ledger.audit().count, 2)
    }

    func testTransparencyTamperDetected() throws {
        let coin = Coin(); try coin.mint("cust", 100_000)
        let ledger = Transparency.TransparencyLedger()
        try ledger.registerBusiness("shop", identified: true)
        _ = try Transparency.businessSale(coin, ledger, seller: "shop", buyer: "cust",
                                          item: Data("a".utf8), amount: 1000, epoch: 1)
        _ = try Transparency.businessSale(coin, ledger, seller: "shop", buyer: "cust",
                                          item: Data("b".utf8), amount: 2000, epoch: 1)
        XCTAssertTrue(ledger.verifyChain())
        // Edit an entry's amount in place: the chain must break (tamper-evident).
        let first = ledger.audit()[0]
        ledger.tamper(at: 0, with: Transparency.Entry(business: first.business, kind: first.kind,
                                                      amount: 999999, fee: first.fee,
                                                      counterparty: first.counterparty,
                                                      epoch: first.epoch, prev: first.prev))
        XCTAssertFalse(ledger.verifyChain())
    }
}
