import XCTest
@testable import AtlasCore

/// Parity with backend/atlas/keys/server_custody.py + the crypto behaviour of the custody layer.
final class ServerCustodyTests: XCTestCase {
    private let policy = try! ThresholdSeal.ThresholdPolicy(n: 3, m: 2)
    private let sel = Data("blinded-recovery-selector".utf8)

    private func nodes(_ ids: String...) -> [ServerCustody.CustodianNode] {
        ids.map { ServerCustody.CustodianNode(nodeID: $0) }
    }
    private func xor(_ a: Data, _ b: Data) -> Data { Data(zip(a, b).map { $0 ^ $1 }) }

    /// Byte-for-byte cross-language parity of the deterministic derivations (locator + seal key),
    /// against vectors generated by the Python reference.
    func testLocatorAndSealKeyMatchPythonVectors() {
        let rkey = Data((0..<32).map { UInt8($0) })            // 000102...1f
        let loc = ServerCustody.locator(recoverySelector: sel, nodeID: "node-a", epoch: 7)
        XCTAssertEqual(loc.map { String(format: "%02x", $0) }.joined(),
                       "55b7e4857efefc147bc3ac4bf598509a831328d4af057b218b79e2d137d8b6b3")
        let sk = ServerCustody.sealKey(recoveryKey: rkey, locator: loc)
        XCTAssertEqual(sk.map { String(format: "%02x", $0) }.joined(),
                       "1a2d6869119ab054a63c542368e31f0567fda1cccbbcd7297394de40ddf3c1ac")
    }

    func testDistributeCollectRoundtrip() throws {
        let serverHalf = Primitives.randomBytes(32), rkey = Primitives.randomBytes(32)
        let pls = try ServerCustody.distribute(serverHalf: serverHalf, nodes: nodes("a", "b", "c"),
                                               policy: policy, recoverySelector: sel, recoveryKey: rkey)
        let got = try ServerCustody.collect(retrieved: [(pls[0].locator, pls[0].blob),
                                                        (pls[2].locator, pls[2].blob)],
                                            policy: policy, recoveryKey: rkey)
        XCTAssertEqual(got, serverHalf)
    }

    func testBelowThresholdFailsClosed() throws {
        let rkey = Primitives.randomBytes(32)
        let pls = try ServerCustody.distribute(serverHalf: Primitives.randomBytes(32),
                                               nodes: nodes("a", "b", "c"), policy: policy,
                                               recoverySelector: sel, recoveryKey: rkey)
        XCTAssertThrowsError(try ServerCustody.collect(retrieved: [(pls[0].locator, pls[0].blob)],
                                                       policy: policy, recoveryKey: rkey))
    }

    func testWrongKeyCannotOpen() throws {
        let serverHalf = Primitives.randomBytes(32), rkey = Primitives.randomBytes(32)
        let pls = try ServerCustody.distribute(serverHalf: serverHalf, nodes: nodes("a", "b", "c"),
                                               policy: policy, recoverySelector: sel, recoveryKey: rkey)
        XCTAssertThrowsError(try ServerCustody.collect(retrieved: [(pls[0].locator, pls[0].blob),
                                                                   (pls[1].locator, pls[1].blob)],
                                                       policy: policy, recoveryKey: Primitives.randomBytes(32)))
    }

    func testRotationReshsaresAndDropsAllOld() throws {
        let serverHalf = Primitives.randomBytes(32), rkey = Primitives.randomBytes(32)
        let old = try ServerCustody.distribute(serverHalf: serverHalf, nodes: nodes("a", "b", "c"),
                                               policy: policy, recoverySelector: sel, recoveryKey: rkey, epoch: 0)
        let (new, drop) = try ServerCustody.rotate(
            retrieved: [(old[0].locator, old[0].blob), (old[1].locator, old[1].blob)],
            allOldLocators: old.map { $0.locator }, policy: policy, recoverySelector: sel,
            recoveryKey: rkey, newNodes: nodes("d", "e", "f"), newEpoch: 1)
        let got = try ServerCustody.collect(retrieved: [(new[0].locator, new[0].blob),
                                                        (new[2].locator, new[2].blob)],
                                            policy: policy, recoveryKey: rkey)
        XCTAssertEqual(got, serverHalf)                                  // same secret survives rotation
        XCTAssertEqual(Set(drop), Set(old.map { $0.locator }))          // all old locators retired
        XCTAssertTrue(Set(old.map { $0.locator }).isDisjoint(with: Set(new.map { $0.locator })))
    }

    func testEndToEndTwoTierRecoveryThroughCustody() throws {
        let seed = Primitives.randomBytes(32)
        let userHalf = Primitives.randomBytes(32)
        let serverHalf = xor(seed, userHalf)
        let rkey = Primitives.randomBytes(32)

        let userShares = Shamir.split(userHalf, n: 3, k: 2)
        let pls = try ServerCustody.distribute(serverHalf: serverHalf, nodes: nodes("a", "b", "c"),
                                               policy: policy, recoverySelector: sel, recoveryKey: rkey)
        let rebuiltUser = Shamir.combine(Array(userShares.prefix(2)))
        let rebuiltServer = try ServerCustody.collect(retrieved: [(pls[0].locator, pls[0].blob),
                                                                  (pls[1].locator, pls[1].blob)],
                                                      policy: policy, recoveryKey: rkey)
        XCTAssertEqual(xor(rebuiltUser, rebuiltServer), seed)
        XCTAssertNotEqual(rebuiltServer, seed)                          // server side alone reveals nothing
    }
}
