// swift-tools-version: 6.0
// AtlasCore — the kit-independent Atlas protocol core, in Swift.
//
// This is the on-device sibling of backend/atlas (Python). It is pure Swift +
// CryptoKit so it builds and `swift test`s on the Mac without the iOS app
// target. The Xcode app (../AtlasApp) imports this package and adds the
// hardware-bound surfaces (CoreBluetooth R10, Secure Enclave, App Attest,
// camera, SwiftUI).
//
// PQC note (§1.3): the hybrid KEM/signature types use CryptoKit's
// quantum-secure APIs (ML-KEM-768, ML-DSA-65, X-Wing). Confirm the exact symbol
// names against your target SDK (see Crypto/CryptoProvider.swift) — Apple's PQC
// surface is recent and the app pins a deployment target accordingly.

import PackageDescription

let package = Package(
    name: "AtlasCore",
    platforms: [
        // CryptoKit PQC (ML-KEM-768, ML-DSA-65, X-Wing) landed in the 2025 SDK, so
        // the deployment target must be iOS 26 / macOS 26 or the symbols report as
        // unavailable. Use the STRING form (not the `.v26` enum case, which does
        // not exist at swift-tools-version 6.0 — that enum caps at .v18).
        .iOS("26.0"), .macOS("26.0"),
    ],
    products: [
        .library(name: "AtlasCore", targets: ["AtlasCore"]),
    ],
    targets: [
        .target(name: "AtlasCore"),
        .testTarget(
            name: "AtlasCoreTests",
            dependencies: ["AtlasCore"],
            // Cross-impl parity vectors generated by the Python core
            // (backend/tools/gen_parity_vectors.py). ParityTests asserts the
            // Swift core reproduces every vector byte-for-byte.
            resources: [.process("Resources")]
        ),
    ]
)
